<h1>How A Great Resume Works</h2>
<p>When you complete your resume and send it out into the world, where does it actually go? What happens to your document between the moment it leaves your desktop and the moment you’re called in for an interview? How do great resumes actually lead to open doors, expanded options, and thriving employer-employee relationships? The answer is based on a complex blend of technology, psychology, economics, and workplace organization, but here’s the simple version.<span style="font-size: 13px; line-height: 16pt;">&nbsp;</span></p>
<p><strong>The Journey of an Effective Resume</strong></p>
<p>Here are all the pit stops your resume will take, broken down in seven easy steps:</p>
<p><strong>Step 1</strong></p>
<p>The resume leaves your possession. You’ve found a job posting you’d like to pursue, a recruiter who shows interest in you, or a contact who wants to pass your information along to a friend. You pass along your resume (with or without an attached letter of introduction) via email, a submission website, or a document sharing app.</p>
<p><strong>Step 2</strong></p>
<p>Your resume enters a database. The recruiter or employer who takes possession of your resume will probably add it to a file or database containing dozens or hundreds of others. Dozens if your resume has gone directly into the hands of the manager who will make a final hiring decision (skip to step 4). Hundreds if the resume has been sent to an HR Office, a general company inbox, or a recruiter who will perform an initial screening for his/her employer clients. &nbsp;</p>
<p><strong>Step 3</strong></p>
<p>Your resume is submitted to a database and shows up in the results of a keyword search. The recruiter, HR manager, or hiring manager who conducts the search will enter keywords with specific phrases that match the needs of the position, like “CPR certified,” “degree in Macroeconomics,” “French fluency,” “Greenville, South Carolina,” or “Senior level sales manager.”</p>
<p><strong>Step 4</strong></p>
<p>If your resume is chosen it will be skimmed. Human eyes will review your carefully polished text for the first time. Chances are, this initial skim will last less than 30 seconds. Most likely, a reviewer’s eyes will move all the way across the first few lines at the top of the page, halfway across the lines in the middle of the page, and only through the subheadings of anything that falls onto the bottom third. If your resume doesn’t pass this initial skim, it probably won’t be looked at again. This is where eRezzy comes in and helps you craft a professional eye-catching resume.</p>
<p><strong>Step 5</strong></p>
<p>If your resume passes the first quick review, it will be picked up again a few hours or days later and given a more careful examination. If it passes muster, it may be handed over to a second or third pair of eyes for perspective and commentary. Details that match the position perfectly (like ideal educational credentials) will be held up against mismatches (like a geographic area outside of commuting distance, or three years of clinical experience instead of the required ten).</p>
<p><strong>Step 6</strong></p>
<p>If your resume survives these conversations and comparisons, it will be moved into a final round of contenders. If the employers can only interview five candidates, and they have 20 resumes, this is where the hard work, attention to detail, and lost sleep you invested in your resume come into play. Unless it's from eRezzy, where we'll provide you with a quality resume in seconds!</p>
<p><strong>Step 7</strong></p>
<p>Once an interview decision is made, your resume’s hardest job will be over. After your phone rings and the interview is scheduled, the rest of the process will be up to you.</p>
<p><strong>The Last Chapter of the Story</strong></p>
<p>Once you’re hired, your resume may be kept on file for the duration of your tenure with the company (and possibly longer). This means that even after you land the position, your resume will still play a minor role in the progress of your career. A resume frome eRezzy can give you greater control of the seven steps above.</p>